const hubspotTemplateBuilderMatchPattern =
	/<!-- Generated by the HubSpot Template Builder - template version (\d+\.\d+) -->/

const hubspotMetaGeneratorMatchPattern =
	/<meta name="generator" content="HubSpot">/

export const matchers = [
	{
		html(html = '') {
			const match = html.match(hubspotTemplateBuilderMatchPattern)

			if (match?.length) {
				return {
					extra: {
						templateVersion: match[1]
					}
				}
			}
		}
	},
	{
		html(html = '') {
			const match = html.match(hubspotMetaGeneratorMatchPattern)

			if (match?.length) {
				return match
			}
		}
	}
]

export const meta = {
	name: 'HubSpot Template Builder',
	site: 'hubspot.com',
	documentation: null,
	description: null
}
